# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLbNPZFuGXnrn2IRQQnQIwelIacCicle
"""

import streamlit as st
import numpy as np
import onnxruntime as ort

@st.cache_resource
def load_model():
    return ort.InferenceSession(r"C:\Users\mohamed\logistic_regression_onnx_app\logistic_model.onnx")

session = load_model()

st.title("Logistic Regression ONNX Model")
st.write("Enter the values separated by commas (e.g. 1.0,2.5,3.6,4.2)")

input_str = st.text_input("Input features:")

if st.button("Predict"):
    try:
        input_array = np.array([list(map(float, input_str.strip().split(',')))], dtype=np.float32)
        input_name = session.get_inputs()[0].name
        ort_inputs = {input_name: input_array}
        pred = session.run(None, ort_inputs)
        st.write("Result:", pred[0][0])
    except Exception as e:
        st.error(f"Error occurred: {e}")